veripool/verilog-mode

tests/autoinst_autonohookup.v, tests_ok/autoinst_autonohookup.v, verilog-mode.el
This PR fixes an issue in #1526 .
When a NOHOOKUP comment is added to an input port which is the last input port in the instantiated module, then each invocation of verilog-mode would append yet another "Templated
AUTONOHOOKUP" comment over and over.
For example:
a3.v
```
module a3(
/*AUTOINPUT*/
/*AUTOOUTPUT*/
);
/* a2 AUTO_TEMPLATE (
.i1(i1), // AUTONOHOOKUP
.o1(o1),
) */
a2 a2( /*AUTOINST*/ );
endmodule
module a2 (
input i1,
output o1
);
endmodule
```
After 3 consecutive invocations would yield (**please notice you have to right-scroll to see the issue**):
```
module a3(
/*AUTOINPUT*/
/*AUTOOUTPUT*/
// Beginning of automatic outputs (from unused autoinst outputs)
output                  o1                      // From a2 of a2.v
// End of automatics
);
/* a2 AUTO_TEMPLATE (
.i1(i1), // …
```
=> Fixed AUTONOHOOKUP case where the port is the last input.

tests/indent_double_curly.v, tests_ok/indent_double_curly.v, verilog-mode.el
verilog-mode.el (verilog-at-constraint-p): Fix regular expression
Add test indent_double_curly.v
=> Fix indentation on double curly brackets (issue #1719)

tests/indent_double_curly.v, tests_ok/indent_double_curly.v, verilog-mode.el
* verilog-mode.el (verilog-at-constraint-p): 
Fix indentation of constructions like `x <= {a, {b, c}};` and `x <= {a[0:1], {b, c}};`.
=> Fix indentation on double curly brackets

tests_ok/autoinst_import2012.v, tests_ok/autowire_import_bug317.v, tests_ok/autowire_pkg_bug195.v, verilog-mode.el
In the following snippet, running `verilog-forward-sexp` while the point is at generate/covergroup/property/sequence keywords will move the point to the end of the file instead of to its corresponding enclosing keyword:
```verilog
module foo
generate
// ...
endgenerate
covergroup
// ...
endgroup
property
// ...
endproperty
sequence
// ...
endsequence
endmodule
```
In addition, running `verilog-forward-sexp` or `verilog-backward-sexp` while over package/endpackage and program/endprogram does not work as expected either. `verilog-forward-sexp` moves the point to the end of the file while `verilog-backward-sexp` does not have any effect:
```verilog
package
// ...
endpackage
program
// ...
endprogram
```
It seems it could be due to a bug in the capture groups numbering of …
=> Fix bug in forward-sexp and backward-sexp for some constructs

tests/indent_list_nil_generate_for.v, tests/indent_list_nil_generate_for2.v, tests/indent_list_nil_generate_if.v, tests/indent_list_nil_generate_if2.v, tests/indent_list_nil_params.v, tests/indent_list_nil_params2.v, tests/indent_list_nil_pkg_class.sv, tests_ok/indent_list_nil_generate_for.v, tests_ok/indent_list_nil_generate_for2.v, tests_ok/indent_list_nil_generate_if.v, tests_ok/indent_list_nil_generate_if2.v, tests_ok/indent_list_nil_params.v, tests_ok/indent_list_nil_params2.v, tests_ok/indent_list_nil_pkg_class.sv, tests_ok/indent_param_1645.v, verilog-mode.el
This PR implements the indentation suggested in #1703 by setting `verilog-indent-lists` to nil.
Currently, if setting `verilog-indent-lists` to nil there are some indentation issues:
```verilog
module foo # (
parameter A = 0,
parameter B = 0,
parameter C = 0
)(
input wire a,
input wire b,
output reg z
);
endmodule
```
gets indentend to:
```verilog
module foo # (
parameter A = 0,
parameter B = 0,
parameter C = 0
)(
input wire a,
input wire b,
output reg z
);
endmodule
```
The patch also takes into account indentation inside generate blocks and function/tasks arguments.
=> Fix indentation if verilog-indent-lists is nil

tests/indent_sv_interface_mp_bug636.sv, tests_ok/autoinoutmodule_iface.v, tests_ok/autoinst_import.v, tests_ok/autoinst_import2012.v, tests_ok/autoinst_interface.v, tests_ok/autoinst_interface_star.v, tests_ok/autoinst_interface_sub.v, tests_ok/autoinst_mplist.sv, tests_ok/autoinst_mplist_child.sv, tests_ok/indent_sv_interface_mp_bug636.sv, verilog-mode.el
This PR fixes alignment of modport declarations.
Related issue: #636
=> Fix alignment of declaration of interfaces with modports

tests/autoinst_param_2d.v, tests/autoinst_vec_nil.v, tests/autoinst_vec_t.v, tests/autoinst_vec_unsigned.v, tests/autowire_merge_bug303.v, tests_ok/autoinst_param_2d.v, tests_ok/autoinst_vec_nil.v, tests_ok/autoinst_vec_t.v, tests_ok/autoinst_vec_unsigned.v, tests_ok/autowire_merge_bug303.v
Hi,
This PR is done as a request on #1775 to split changes not related to comment aligning in a different commit.
A colon was missing on 5 tests after module declaration and first line of variable declarations was being indented incorrectly.
=> Add a semicolon after module declaration on tests to fix indentation.

tests/indent_macro_comment.v, tests/indent_macro_ignore_multiline.sv, tests/indent_macro_ignore_regexp.sv, tests/label_macro.v, tests_ok/indent_macro_comment.v, tests_ok/indent_macro_ignore_multiline.sv, tests_ok/indent_macro_ignore_regexp.sv, tests_ok/label_macro.v, verilog-mode.el
Hi,
This PR adds support to ignore  indentation of multiline defines and custom regexps.
Related issues: #1082, #922, #885
=> Add indentation ignore of multiline defines and custom regexps

tests/align_decl_comments_spacing_0.sv, tests/align_decl_comments_spacing_10.sv, tests_ok/align_decl_comments_spacing_0.sv, tests_ok/align_decl_comments_spacing_10.sv, verilog-mode.el
Hi,
This PR adds the customizable variable `verilog-declaration-comments-distance` to adjust the spacing between the longest declaration and the beginning of aligned comments, previously fixed to 1 space.
I also added two tests, similar to the `align_decl_comments.sv` test, but with spacing set to 0 and 10 respectively.
=> Add variable to adjust aligned comment distance in declarations.

tests_ok/escape_a.v, verilog-mode.el
Hi,
This PR fixes the function `verilog-pretty-expr` when cursor is at a declaration. 
It adds some cleaning to the `verilog-indent-declaration`, replacing some ifs without an else clause with `(when condition ...)` and indenting accordingly.
It also includes additional checks to set proper boundaries when looking for previous declaration as a template, as part of the process of the expression prettifying. Otherwise, declarations outside of a module port list get aligned with expressions inside module port lists, e.g:
```verilog
module ExampOutputEvery (
/*AUTOOUTPUTEVERY*/
// Beginning of automatic outputs (every signal)
output o,
output tempa,
output tempb,
// End of automatics
input  i
);
wire tempa = i;
wire tempb = tempa;
wire o     = tempb;
endmodule
```
This would be the result …
=> Fix verilog-pretty-expr on declarations and update related tests

tests_ok/indent_genmod.v, tests_ok/indent_replicate.v, verilog-mode.el
Hi,
While working on PR #1780 I noticed that a declaration that should get aligned for `indent_replicate.v` actually did not. After a bit of debugging I found the issue was caused by the declaration being right after the `begin` keyword if `verilog-indent-lists` was set to t (its default value). 
I applied part of the changes of 2adbba2 also for `verilog-indent-lists` set to t and it happened to also fix the `indent_genmod.v` test mentioned in #1163. Even though that issue shows as closed it seems this test was still broken, but it would be nice if it could be confirmed.
Thanks!
=> Fix indentation of instances and declarations after 'begin'

tests/indent_comments_bug1717.v, tests_ok/autoarg_comment.v, tests_ok/autoinst_bits_lba_gi.v, tests_ok/indent_comments_bug1717.v, tests_ok/verilint_113.v, verilog-mode.el
Hi,
This PR fixes indentation of next line when there are comment delimiters inside a comment.
Related issue: #1717
=> Fix indentation after double comment.

verilog-mode.el
Hi,
This PR should not add any functional change. 
First commit removes unused declaration regexps and does some refactoring to group all declaration regexp related code into one function. This should make functions like `verilog-pretty-declarations` and `verilog-pretty-expr` more easily maintainable.
Second commit removes some commented code on previous functions and fixes a typo on one of the variable names.
Since this is somehow a code cleaning PR I thought both commits could be squashed into a single one. What do you think @wsnyder ?
Thanks!
=> Refactor declaration regexps and some code cleaning

verilog-mode.el
Hi,
This PR partially fixes issue #1752.
The changes in the updated regexp that @kaushalmodi proposed to detect signed/unsigned declarations were included after refactoring in 72c2b1f. However after this commit there was a bug in `verilog-declaration-varname-matcher` when trying to execute `forward-sexp` over a closing brace/bracket/parenthesis.
The PR also avoids fontify overriding of reserved keywords on variable declarations.
It still fontifies wrongly typedef enum declarations since these need some additional debugging (possibly in future PRs).
Thanks!
=> Fix fontifying of variable names and overriding of keywords.

verilog-mode.el
Hi,
This PR fixes a bug when using `verilog-backward-sexp`. Considering the following snippet:
```verilog
constraint addr_range {
(atype == low ) -> addr inside { [0 : 15] };  //  line 1 comment
(atype == mid ) -> addr inside { [16 : 127]}; //  line 2 comment
(atype == high) -> addr inside {[128 : 255]}; //  line 3 comment
}
```
If point is after `}` and `verilog-backward-sexp` is executed, the cursor will move to the beginning of line 3 comment instead of to its corresponding opening brace. With this fix parenthetical expressions have higher precedence in `verilog-backward-sexp` cond block and it works as expected.
Thanks!
=> Add precedence to paren expressions for sexp funcs navigation.

tests/autoreset_latch.v, tests/indent_enum.v, tests/indent_list_nil_typedef_enum.sv, tests/indent_struct.v, tests/indent_typedef_enum.sv, tests_ok/autoreset_latch.v, tests_ok/autowire_pkg_bug195.v, tests_ok/indent_enum.v, tests_ok/indent_list_nil_typedef_enum.sv, tests_ok/indent_modeln.v, tests_ok/indent_typedef_enum.sv, tests_ok/v2k_typedef_yee_inc.v, verilog-mode.el
Hi,
This PR fixes the alignment of (typedef) enums and structs declarations. Since these were being detected wrongly, the new changes just ignore them when running `verilog-pretty-declarations`. However, fields inside a struct still get aligned properly.
For example, considering the following example from #1752 discussion:
```verilog
module pr_example;
logic correct_0;
logic signed [1:0] incorrect_0;
logic correct_1;
logic signed [1:0] incorrect_1;
typedef enum logic [1:0]
{STATE_0,
STATE_1,
STATE_2,
STATE_3} t_incorrect_2;
t_incorrect_2 incorrect_3;
endmodule
```
After indenting and executing `verilog-pretty-declarations` this is the result before the PR:
```verilog
module pr_example;
logic              correct_0;
logic signed [1:0] incorrect_0;
logic              correct_1;
logic signed …
```
=> Fix alignment of structs and enums.

tests/indent_list_nil_continued_line.sv, tests_ok/indent_list_nil_continued_line.sv, tests_ok/indent_list_nil_typedef_enum.sv, verilog-mode.el
Hi,
The following PR fixes indentation of enums and continued lines of assignments when `verilog-indent-lists` is set to nil.
These snippets from `tests_ok/indent_list_nil_continued_line.sv` are indented correctly but do not get aligned properly after running `verilog-pretty-expr`. This is an already existing issue that will be fixed in another PR:
```verilog
startc_c           <= (valid && (state == THE_START));
end_c              <= (valid && (state == THE_END));
valid_c            <= (valid &&
(state != IDLE) &&
(state != SKIP_DATA));
```
```verilog
valid_c             <= { valid ,
(state != IDLE) ,
(state != SKIP_DATA)
};
```
These are the results after indenting without `verilog-pretty-expr`:
```verilog
startc_c           <= (valid && (state == THE_START));
end_c              <= …
```
=> Fix indentation of assignments and enums with indent-lists nil

tests/sol_asense.v, tests_ok/autoreset_cond.v, tests_ok/autoreset_equal_extra.v, tests_ok/indent_list_nil_continued_line.sv, tests_ok/testcases.v, verilog-mode.el
Hi,
This PR prevents the function `verilog-pretty-expr` from executing on multiline assignments. 
In the example from previous PR #1790 the following snippet was wrongly aligned due to the presence of `!=` in the multiline assignment:
```verilog
startc_c           <= (valid && (state == THE_START));
end_c              <= (valid && (state == THE_END));
valid_c            <= (valid &&
(state != IDLE) &&
(state != SKIP_DATA));
```
After the PR:
```verilog
startc_c <= (valid && (state == THE_START));
end_c    <= (valid && (state == THE_END));
valid_c  <= (valid &&
(state != IDLE) &&
(state != SKIP_DATA));
```
Thanks!
=> Prevent verilog-pretty-expr from executing on multiline assignments

tests_ok/indent_unique_case-1.v, tests_ok/inject_first.v, verilog-mode.el
Hi,
This PR fixes a bug in `verilog-pretty-expr` that produced a wrong alignment of statements when there were comparison operators nearby. For example:
```verilog
DD_CMRD : begin
uuuuu         <= 1'b1;
if (jjjj_left <= 4) begin
qwerty <= 1'b1;
end
```
After the PR:
```verilog
DD_CMRD : begin
uuuuu <= 1'b1;
if (jjjj_left <= 4) begin
qwerty <= 1'b1;
end
```
This PR will also help simplifying implementing a feature that will allow aligning expressions of continuous assignments.
Thanks!
=> Fix bug in boundaries of verilog-pretty-expr.

tests/align_assign_expr.sv, tests_ok/align_assign_expr.sv, verilog-mode.el
Hi,
This PR adds support to align expressions of continuous assignments. This is configured by the use of a variable (`verilog-align-assign-expr`) that is enabled by default.
Considering the following snippet:
```verilog
assign ExtraOut = 3'h0;
assign SubOut = 3'h0;
assign active_low_l = 4'h0;
assign ignored_by_regexp = 4'h0;
```
Setting `verilog-align-assign-expr` to non-nil and running `verilog-pretty-expr` results in:
```verilog
assign ExtraOut          = 3'h0;
assign SubOut            = 3'h0;
assign active_low_l      = 4'h0;
assign ignored_by_regexp = 4'h0;
```
The PR also adds a test to ensure that disabling the feature keeps backwards compatibility (`tests/align_assign_expr_nil.sv`).
Cheers!
=> Add support to align expressions of continuous assignments

tests/indent_list_nil_param_port_list.sv, tests/param_port_list.sv, tests_ok/indent_list_nil_param_port_list.sv, tests_ok/param_port_list.sv, verilog-mode.el
Hi,
This PR improves indentation of module/interfaces/program/classes parameter lists when the variable `verilog-indent-lists` is set to nil. 
If the first parameter is in the same line as the opening parenthesis indentation will keep this alignment for the rest of parameters, as if `verilog-indent-lists` was non-nil.
This was before the PR:
```verilog
class parameterized_class #(type T1=int,
type T2=int,
type T3=int) extends base_class;
```
This is the result after the PR:
```verilog
class parameterized_class #(type T1=int,
type T2=int,
type T3=int) extends base_class;
```
If the parameter is in the next line after the parenthesis previous behavior is maintained:
```verilog
class parameterized_class #(
type T1=int,
type T2=int,
type T3=int) extends base_class;
```
Thanks!
=> Improve indentation of defun parameters when indent-lists is nil

tests_ok/autosense_if_else.v, tests_ok/autosense_venkataramanan_begin.v, tests_ok/autotieoff_assign.v, tests_ok/autotieoff_inoutmod.v, tests_ok/autowire_pkg_bug195.v, tests_ok/autowire_req_sw.v, tests_ok/hangcase.v, tests_ok/indent_bracket.v, tests_ok/inject_inst_empty_ports.v, tests_ok/inject_inst_endparen.v, tests_ok/inject_inst_net_case.v, tests_ok/inject_inst_param.v, tests_ok/inject_path_sub.v, verilog-mode.el
Hi,
This PR prevents `verilog-pretty-expr` from aligning lines that do not contain statements that can be aligned (e.g. continuous assignments when `verilog-align-assign-expr` is nil).
Almost all the changes revert the `test_ok/*` tests alignment made by `verilog-pretty-expr` on `else` and `assign` statements. 
Thanks!
=> Fix bug in alignment of expressions

tests/align_bug1272.sv, tests/align_bug585.sv, tests/align_bug960.sv, tests/indent_replicate_bug955.sv, tests_ok/align_bug1272.sv, tests_ok/align_bug585.sv, tests_ok/align_bug960.sv, tests_ok/indent_replicate_bug955.sv
Hi,
This PR adds test files for various issues:
- #585
- Fixed after #1798 
- #960
- Works fine
- #955 
- Works fine
- #1272 
-  Everything indents and aligns correctly except for package imports between module identifier and parameter list. Even though this seems supported by simulators (tested in Xcelium 19.09) I do not think it would be worth the effort looking into it since package importing in the unit space and after ports list already indents correctly.
```verilog
module alignment_test
import bar_pkg2::*;
import foo_pkg2::*;
#(
```
Thanks!
=> Tests: add testcases for issues 1272, 960, 955 and 585

tests/indent_generate_bug1404.sv, tests/indent_generate_case.v, tests/indent_generate_for.v, tests/indent_generate_if.v, tests_ok/autoreset_inf_bug325.v, tests_ok/indent_generate_bug1404.sv, tests_ok/indent_generate_case.v, tests_ok/indent_generate_for.v, tests_ok/indent_generate_if.v, verilog-mode.el
Hi,
This PR fixes a bug in the function `verilog-in-generate-region-p`. 
```verilog
module foo;
some_if my_if;
// If point is here, `verilog-in-generate-region-p' returns t:
//  - Wrongly detects the if of the interface type as if it was a
//    keyword due to regexp word boundaries not set properly
generate begin : test_gen
if (CONDITION == "TRUE") begin
always @(posedge Clk) begin
if (!Rst_n) begin
signal <= 0;
end else begin
signal <= 1;
end
end
end else if (CONDITION == "FALSE") begin
always @(posedge Clk) begin
if (!Rst_n) begin
signal <= 0;
end else begin
signal <= 2;
end
end
end else begin
always @(posedge Clk) begin
if (!Rst_n) begin
signal <= 0;
end else begin
signal <= 3;
end
end
end
end : test_gen
endgenerate
// If point is here, `verilog-in-generate-region-p' returns t:
//  - …
```
=> Fix bug in verilog-in-generate-region-p

tests/indent_assert_property.v, tests_ok/indent_assert_property.v, verilog-mode.el
…837)
* verilog-mode.el (verilog-property-re, verilog-beg-of-statement, verilog-calc-1): Concurrent SVA statement pattern-matching learns 'restrict property' and 'cover sequence' expression for proper indentation around those constructs. This addresses more patterns in IEEE 1800-2017's 'concurrent_sasertion_statement' grammar.
* tests{,_ok}/indent_assert_property.v: Add test cases from GitHub user 'pbing'
We appreciate your contributing to Verilog-Mode.
By contributing you agree this code will be licensed under the GNU Public License.
Please check your github name is set to your real name (click on your avatar icon in upper right, then "settings" then "Name".) This should match your system's ~/.gitconfig user name.
=> Fix indentation of concurrent properties and sequences (#1836) (#1837)
